# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6972491ec50349c7e24e3f41438f8d1a61bbcab1b654100282aaedadc581cb520a716abc315b898e6f31be69385ff0d77c5e97601c767bf3b3f6630a14711d6d

test:
  secret_key_base: 97eb48aab5eef99bc7664dcb070ecc22cee06baf180eaa9aa0b85fc6535ba2997f69df2bdf2c9cbd6d022bc078ca7aaea63760861bd1ee9b046a00239199a378

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
